on: push
name: Deploy Web 

jobs:
  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: install-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: install-dependency
        run: npm install
      - name: build
        run: npm run build
      - name: upload-artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build
      - name: deploy
        uses: actions/deploy-pages@v4